### ISSUE TITLE
crab docs 目录调整

### ISSUE THREAD

**Issue by 1022ranji** [darwinia-network/crab-docs#89]
1. introduce
2. Substrate-based Crab Chain
   - Parameters
   - Tools
   - Native Tokens
   - How to Create an Account
   - How to become a validator
   - How to become a nominator
   - How to run a node
   - Ecosytem
       - Ropsten Bridge(create an issue?)
       - Exchange Access Guide
3. EVM-Compatible Crab Smart Chain
    - Get started(DVM -> Introduction)
          - Development Node
          - Connect to Pangolin
          - Connect to Crab
    - Network RPC 
    - Tokens
    - Wallets
          - Metamask
          - Smart Apps(link to tutorials)
     - Builders
         - Interact
         - Tools
         - InAdvanced
            - DVM Address
            - System Contract
         - Ecosystem
             - indexers
                  - Using the graph
              - Oracles
                  - chainlink
4. Tool Tutorials
    - Crab Gas Token
    - Wormhole User Guide
    - Smart App User Guide
5. FAQ
   - Substrate address vs DVM Address

**Comment by fewensa** [comment]
https://github.com/darwinia-network/crab-docs/blob/c7cf706bda907eb87f02f475434e5a633f28d45e/airdrop/api/authorization.ts#L10

If `Connect to Crab` URL changed please don't forget update there.
